# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bike Tag
email: michael@jackpine.me
description: > # this means to ignore newlines until "baseurl:"
  Bike Tag is a game for discovering and sharing secret spots in your city.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://biketag.jackpine.me" # the base hostname & protocol for your site
twitter_username: ikawe
github_username:  michaelkirk

# Build settings
markdown: kramdown
